# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generates iOS screenshots"
  lane :screenshots do
    capture_screenshots(
      project: "DaysLeft.xcodeproj",
      scheme: "UI Tests",
      derived_data_path: "~/Library/Developer/Xcode/DerivedData",
      devices: ["iPhone 8 Plus", "iPhone 11 Pro Max", "iPad Pro (12.9-inch) (5th generation)"],
      languages: ["en-US"],
      clear_previous_screenshots: false,
      cloned_source_packages_path: "SourcePackages"
    )
  end

  desc "Runs the unit tests"
  lane :test do
    run_tests(
      project: "DaysLeft.xcodeproj",
      device: "iPhone 11 Pro Max",
      scheme: "DaysLeft",
      result_bundle: true,
      output_directory: "fastlane/test_output/Networking",
      derived_data_path: "~/Library/Developer/Xcode/DerivedData",
      cloned_source_packages_path: "SourcePackages"
    )
  end
end

