# Uncomment the lines below you want to change by removing the # in the beginning

devices(["iPhone 8 Plus", "iPhone 11 Pro Max", "iPad Pro (12.9-inch) (5th generation)"])
languages(["en-US"])
scheme("UI Tests")
output_directory("./screenshots")
clear_previous_screenshots(false)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
# override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
